name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup GLFW
      run: sudo apt-get update && sudo apt-get install -yq libglfw3-dev && sudo apt-get install -yq libglfw3 && sudo apt-get install -yq xorg-dev
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

