name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: OpenGL Actions
      uses: NishkarshRaj/OpenGL_Actions@1.0
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

